---
title: "acp_projet_farms"
author: " "
date: ""
output: html_document
---

# 

Importation du jeu de données.

------------------------------------------------------------------------

```{r}
train <- read.csv("C:/Users/laasi/OneDrive/Bureau/MIASHS/MASTER/m1/projet_farms/data/farms_train.csv")
test  <- read.csv("C:/Users/laasi/OneDrive/Bureau/MIASHS/MASTER/m1/projet_farms/data/farms_test.csv")

```

------------------------------------------------------------------------

a)  Calculez la matrice des corrélations R à partir de la matrice des données centrées-réduites Z, en pondérant les lignes par 1/n.

```{r}
n<- nrow(train)
colonnes <- c("R2","R7","R8","R17","R22","R32")

# Matrice des corrélations
R <- cor(train[, colonnes])

# Afficher la matrice
round(R, 3)


```

------------------------------------------------------------------------

```{r}
library(corrplot)
corrplot(R, method="color", addCoef.col="black")

```

b)  Effectuez la décomposition spectrale de R et en déduisez la matrice V des vecteurs propres de R triés par ordre décroissant des valeurs propres.\
    Vérifiez que les vecteurs propres sont bien normés à 1 et orthogonaux (orthonormés).

```{r}
# Décomposition spectrale de R
e <- eigen(R)

# Valeurs propres
lambda <- e$values
lambda

# Matrice des vecteurs propres (chaque colonne = un vecteur propre)
V <- e$vectors
V

round(t(V) %*% V, 3)  # doit donner la matrice identité I_6
sum(V[,1]*V[,1])      # doit = 1
sum(V[,1]*V[,2])  

```

```{r}
install.packages("FactoMineR")   # si pas déjà installé
install.packages("factoextra")   # pour la visualisation

library(FactoMineR)
library(factoextra)
```

```{r}
res.pca <- PCA(train[, colonnes], scale.unit = TRUE, graph = FALSE)

# Afficher les composantes principales (coordonnées des individus)
head(res.pca$ind$coord)

# Afficher la variance expliquée par chaque composante
res.pca$eig

```

------------------------------------------------------------------------

```{r}
library(factoextra)

#Variance expliquée par chaque composante
fviz_eig(res.pca, addlabels = TRUE, ylim = c(0, 50))
```

```{r}
# Valeurs propres
eig_val <- res.pca$eig

# Pourcentage de variance cumulée
cum_var <- eig_val[,"cumulative percentage of variance"]
cum_var

# Valeurs propres et variance cumulée
eig_val <- res.pca$eig
cum_var <- eig_val[,"cumulative percentage of variance"]

# Plot variance cumulée
plot(cum_var, type="b", pch=19, col="blue",
     xlab="Composante principale",
     ylab="Variance cumulée (%)",
     main="Variance cumulée des composantes principales")
grid()

```

```{r}
fviz_pca_var(res.pca,
             col.var = "contrib",        # couleur selon la contribution
             gradient.cols = c("blue","yellow","red"),
             repel = TRUE,               # éviter le chevauchement des labels
             axes = c(1,2))              # PC1 et PC2
```
